# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IMG',
        ),
    ]
