# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20170605_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sensor', models.CharField(max_length=50, verbose_name='Sensor')),
                ('Time', models.CharField(max_length=50, verbose_name='Time')),
                ('Tpye', models.CharField(max_length=50, verbose_name='Tpye')),
                ('Data', models.CharField(max_length=50, verbose_name='Data')),
            ],
        ),
    ]
