# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20170627_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Tpye',
        ),
    ]
